[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "shared"
version = "0.1.0"
description = "Pacote compartilhado do Lykos"
requires-python = ">=3.10"
dependencies = [
    "Django>=5.1.0"
]

# ğŸ‘‡ A MÃGICA ESTÃ AQUI: Diz onde achar o cÃ³digo
[tool.setuptools.packages.find]
where = ["."]  # Procura na raiz da pasta que foi copiada
include = ["shared*"]  # Inclui a pasta interna 'shared' e subpastas
namespaces = false # Desabilita namespace packages se nÃ£o precisar (geralmente safer false)